### ISSUE TITLE
nolib releases

### ISSUE THREAD

**Issue by vvv444** [Phanx/BetterBattlePetTooltip#10]
Hi,

Is there a reason why you don't provide "nolib" releases? Any chance you can consider enabling these? I can provide you with a patch if you like.

Best regards!

**Comment by vvv444** [comment]
I took a look at the rep. As far as I understand it is a one line change in the pkgmeta file :-)

**Comment by Phanx** [comment]
I'm no longer using the Curse packager to build my ZIP files, and -nolib ZIPs that are uploaded manually (through the developer API, in my case) don't actually count as "nolib packages" for the Curse Client -- you'd still get the full package through the Curse Client.

Until Curse changes this behavior, there's no point in creating and uploading -nolib ZIPs. Even if the file is available, you won't get it unless you're installing and updating by hand, and if you're already updating by hand, then it's just as easy to delete the Libs subfolder by hand.

**Comment by vvv444** [comment]
I see. This is unfortunate :-(
But why don't you use Curse packager anymore?

**Comment by vvv444** [comment]
And thanks for the prompt answer!

**Comment by Phanx** [comment]
> But why don't you use Curse packager anymore?

Short version: Because a 3P packager works better, and the whole process 
is simpler.

Long version: When I updated Grid for 7.0, it ran headfirst into a 
long-standing bug in the Curse packager. While that bug did actually get 
fixed about a week later, it had been around for *years* before that, so 
I had no reason to think it was going to get fixed now. Rather than keep 
100,000 users waiting (and getting random WotLK-era versions installed 
by the Curse Client in the meantime) or waste my time manually building 
ZIPs, I tried out a third-party packager script, and it worked so well 
that I decided to use it for all of my addons going forward.

- It works immediately, while the Curse packager is often delayed. (On 
its own, this is not a big deal, but it becomes a problem when...)

- If it doesn't work for some reason, I know right away (instead of 
having to wait hours and wonder if it's still queued or actually failed) 
and I can just fix it, because it's just a shell script living on my 
computer, rather than a black box on Curse's servers.

- It also uploads the ZIP to WoWInterface at the same time, so I no 
longer need to run a different third-party app on Heroku (yet another 
site) and set up webhooks on all my repos to automate waiting for the 
Curse packager, downloading the ZIP from Curse, and re-uploading it on 
WoWI. (You might think doing that by hand isn't much work, and for one 
or two addons, it's not, but when you have 50 addons to update every 
patch, the tedium quickly reaches critical levels of nope.)

- It actually doesn't require me to maintain a remote repo at all, so 
not only do I no longer need to push to Curse in addition to GitHub, but 
I also don't even need to push to GitHub. I could use any Git host I 
wanted, or none at all and just keep everything local. (I will, however, 
continue pushing to GitHub, because that has other benefits like issue 
tracking and letting people review my code and submit patches.)

**Comment by Phanx** [comment]
> Also, I don't know why you claim that manual upload of -nolib ZIPs does not work. I've tested it with uploading manual alpha version for addon that I author and it was recognized properly by Curse Client: https://wow.curseforge.com/addons/guildnotesetter/files/

It's not recognized properly. All (alpha) users are getting that -nolib ZIP right now, not just -nolib users, because it's the latest file on your project.

If you look at the files list for a project using the packager, you'll note the packager adds the -nolib file first, then the regular file; the last file uploaded is always the default download for your project (within a given release level), but internally the packager does some magic to flag XYZ-nolib.zip as the -nolib version of XYZ.zip.

However, if you do that manually -- upload XYZ-nolib.zip first, then XYZ.zip -- no such magic occurs, everyone gets XYZ.zip, and nobody gets XYZ-nolib.zip unless they go to the file listing on WowAce/CurseForge and click on it manually.

**Comment by vvv444** [comment]
Wow, I see you have tested it all :-)
But was this bug (with manual nolib uploads) officially reported?
