### ISSUE TITLE
Battle pet tooltip info being added to items in profession crafting window.

### ISSUE THREAD

**Issue by Tykwer** [Phanx/BetterBattlePetTooltip#4]
Hi,

I'm running BBPT 6.1.0.22.  As of 6.2, whenever I open a crafting window and hover reagents needed for a particular item, BBPT is applying its tooltip to the items, showing a rare quality border and a "Collected: Level 1" message.  It seems to be superceding all of my other tooltip addons as well, such as Altoholic, that would normally give me quantity and value information in the tooltip.  The problem persists across all my characters, and happens in all profession windows.

Here's a screenshot: http://i.imgur.com/rgNhYrM.jpg

Thanks very much for your work on this addon!

Matt

Edit: I noticed that the BBPT border and info are being applied to any item in a profession window, not just the reagents.  If you hover the item to be crafted it does it as well.  Thanks!

**Comment by vvv444** [comment]
Hi Tykwer,

That is strange... Are you sure you are using version 6.1.0.22? From the screenshot I would suppose it is an older version.

Anyway, I also bumped into this and fixed it. The fix is changing line 296 in Core.lua file from:

`	if type(species) == "string" and not PetNameToSpecies[species] then return end`
to
`	if type(species) == "string" and (species == "" or not PetNameToSpecies[species]) then return end`

Can you please check if this solves the problem for you?

Thanks!

**Comment by Tykwer** [comment]
Yes, that fixed it.  Thanks very much!

Matt

**Comment by Phanx** [comment]
Fixed in 6.2.0.23
